version: "3.9"

services:
  ims.api:
    build:
      context: .
      dockerfile: IMS.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;
        Database=IMS_DB;
        User Id=sa;
        Password=Strong@123;
        TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong@123"
    ports:
      - "1433:1433"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
